<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title> Page non trouv&eacute;e </title>
<!---CSS Files-->
<link rel="stylesheet" href="css/master.css">
<!---Fonts-->
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
</head>
<body>
<div class="header">
<a href="index.php"><img src="img/logo.png" alt="Logo"></a>
</div>
<div class="content container_12">
<h1 id="error-heading">404</h1>
<p id="error-desc">Page non trouv&eacute;e.</p>
<p id="error-back"><a href="index.php">Retour</a></p>
</div>
</body>
</html>